class Movie {
  String title;
  String genre;
  String duration;
  String overview;
  String releaseDate;
  String year;
  String country;
  String director;
  String story;
  String character;
  String screenplay;
  int userScores;
  String poster;

  Movie({
    required this.title,
    required this.genre,
    required this.duration,
    required this.overview,
    required this.releaseDate,
    required this.year,
    required this.country,
    required this.director,
    required this.story,
    required this.character,
    required this.screenplay,
    required this.userScores,
    required this.poster,
  });
}

var movieList = [
  Movie(
    title: 'Alita: Battle Angel',
    genre: 'Action, Science Fiction, Adventure',
    duration: '2h 2m',
    overview:
    'When Alita awakens with no memory of who she is in a future world she does not recognize, she is taken in by Ido, a compassionate doctor who realizes that somewhere in this abandoned cyborg shell is the heart and soul of a young woman with an extraordinary past.',
    releaseDate: '02/14/2019',
    year: '2019',
    country: 'US',
    director: 'Robert Rodriguez',
    story: 'Robert Rodriguez',
    character: 'Laeta Kalogridis',
    screenplay: 'James Cameron, Laeta Kalogridis',
    userScores: 71,
    poster: 'images/poster_alita.jpg',
  ),
  Movie(
    title: 'Aquaman',
    genre: 'Action, Adventure, Fantasy',
    duration: '2h 24m',
    overview:
    'Once home to the most advanced civilization on Earth, Atlantis is now an underwater kingdom ruled by the power-hungry King Orm. With a vast army at his disposal, Orm plans to conquer the remaining oceanic people and then the surface world. Standing in his way is Arthur Curry, Orm\'s half-human, half-Atlantean brother and true heir to the throne.',
    releaseDate: '12/21/2018',
    year: '2018',
    country: 'US',
    director: 'James Wan',
    story: 'James Wan, Will Beall, Geoff Johns',
    character: 'Paul Norris, Mort Weisinger',
    screenplay: 'David Leslie Johnson-McGoldrick',
    userScores: 69,
    poster: 'images/poster_aquaman.jpg',
  ),
  Movie(
    title: 'Bohemian Rhapsody',
    genre: 'Music, Drama',
    duration: '2h 15m',
    overview:
    'Singer Freddie Mercury, guitarist Brian May, drummer Roger Taylor and bass guitarist John Deacon take the music world by storm when they form the rock \'n\' roll band Queen in 1970. Hit songs become instant classics. When Mercury\'s increasingly wild lifestyle starts to spiral out of control, Queen soon faces its greatest challenge yet – finding a way to keep the band together amid the success and excess.',
    releaseDate: '11/02/2018',
    year: '2018',
    country: 'US',
    director: 'Bryan Singer',
    story: 'Anthony McCarten, Peter Morgan',
    character: 'Peter Morgan',
    screenplay: 'Anthony McCarten',
    userScores: 80,
    poster: 'images/poster_bohemian.jpg',
  ),
  Movie(
    title: 'Cold Pursuit',
    genre: 'Action, Crime, Thriller',
    duration: '1h 59m',
    overview:
    'The quiet family life of Nels Coxman, a snowplow driver, is upended after his son\'s murder. Nels begins a vengeful hunt for Viking, the drug lord he holds responsible for the killing, eliminating Viking\'s associates one by one. As Nels draws closer to Viking, his actions bring even more unexpected and violent consequences, as he proves that revenge is all in the execution.',
    releaseDate: '02/08/2019',
    year: '2019',
    country: 'US',
    director: 'Hans Petter Moland',
    story: 'Hans Petter Moland',
    character: 'Frank Baldwin',
    screenplay: 'Frank Baldwin',
    userScores: 66,
    poster: 'images/poster_cold_persuit.jpg',
  ),
  Movie(
    title: 'Creed II',
    genre: 'Drama',
    duration: '2h 10m',
    overview:
    'Between personal obligations and training for his next big fight against an opponent with ties to his family\'s past, Adonis Creed is up against the challenge of his life.',
    releaseDate: '11/21/2018',
    year: '2018',
    country: 'US',
    director: 'Steven Caple Jr.',
    story: 'Cheo Hodari Coker, Sascha Penn',
    character: 'Sylvester Stallone',
    screenplay: 'Sylvester Stallone, Juel Taylor',
    userScores: 69,
    poster: 'images/poster_creed.jpg',
  ),
  Movie(
    title: 'Fantastic Beasts: The Crimes of Grindelwald',
    genre: 'Adventure, Fantasy, Drama',
    duration: '2h 14m',
    overview:
    'Gellert Grindelwald has escaped imprisonment and has begun gathering followers to his cause—elevating wizards above all non-magical beings. The only one capable of putting a stop to him is the wizard he once called his closest friend, Albus Dumbledore. However, Dumbledore will need to seek help from the wizard who had thwarted Grindelwald once before, his former student Newt Scamander, who agrees to help, unaware of the dangers that lie ahead. Lines are drawn as love and loyalty are tested, even among the truest friends and family, in an increasingly divided wizarding world.',
    releaseDate: '11/16/2018',
    year: '2018',
    country: 'US',
    director: 'David Yates',
    story: 'David Yates',
    character: 'J.K. Rowling',
    screenplay: 'J.K. Rowling',
    userScores: 69,
    poster: 'images/poster_crimes.jpg',
  ),
  Movie(
    title: 'Glass',
    genre: 'Thriller, Drama, Science Fiction',
    duration: "2h 9m",
    overview:
    'In a series of escalating encounters, former security guard David Dunn uses his supernatural abilities to track Kevin Wendell Crumb, a disturbed man who has twenty-four personalities. Meanwhile, the shadowy presence of Elijah Price emerges as an orchestrator who holds secrets critical to both men.',
    releaseDate: '01/18/2019',
    year: '2019',
    country: 'US',
    director: 'M. Night Shyamalan',
    story: 'M. Night Shyamalan',
    character: 'M. Night Shyamalan',
    screenplay: 'M. Night Shyamalan',
    userScores: 75,
    poster: 'images/poster_glass.jpg',
  ),
  Movie(
    title: 'Avengers: Infinity War',
    genre: 'Adventure, Action, Science Fiction',
    duration: "2h 29m",
    overview:
    'As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.',
    releaseDate: '04/27/2018',
    year: '2018',
    country: 'US',
    director: 'Anthony Russo, Joe Russo',
    story: 'Joe Russo',
    character: 'Anthony Russo',
    screenplay: 'Stephen McFeely, Christopher Markus',
    userScores: 88,
    poster: 'images/poster_infinity_war.jpg',
  ),
  Movie(
    title: 'Master Z: Ip Man Legacy',
    genre: 'Action',
    duration: "1h 47m",
    overview:
    'Following his defeat by Master Ip, Cheung Tin Chi tries to make a life with his young son in Hong Kong, waiting tables at a bar that caters to expats. But it\'s not long before the mix of foreigners, money, and triad leaders draw him once again to the fight.',
    releaseDate: '12/26/2018',
    year: '2018',
    country: 'TW',
    director: 'Yuen Woo-ping',
    story: 'Yuen Woo-ping',
    character: 'Edmond Wong',
    screenplay: 'Edmond Wong, Chan Tai-Li',
    userScores: 72,
    poster: 'images/poster_master_z.jpg',
  ),
  Movie(
    title: 'Overlord',
    genre: 'Horror, War, Science Fiction',
    duration: "1h 50m",
    overview:
    'France, June 1944. On the eve of D-Day, some American paratroopers fall behind enemy lines after their aircraft crashes while on a mission to destroy a radio tower in a small village near the beaches of Normandy. After reaching their target, the surviving paratroopers realise that, in addition to fighting the Nazi troops that patrol the village, they also must fight against something else.',
    releaseDate: '11/09/2018',
    year: '2018',
    country: 'US',
    director: 'Julius Avery',
    story: 'Billy Ray',
    character: 'Mark L. Smith',
    screenplay: 'Billy Ray, Mark L. Smith',
    userScores: 70,
    poster: 'images/poster_overlord.jpg',
  ),
  Movie(
    title: 'Spider-Man: Into the Spider-Verse',
    genre: 'Action, Adventure, Animation, Science Fiction, Comedy',
    duration: "1h 57m",
    overview:
    'Miles Morales is juggling his life between being a high school student and being a spider-man. When Wilson \'Kingpin\' Fisk uses a super collider, others from across the Spider-Verse are transported to this dimension.',
    releaseDate: '12/14/2018',
    year: '2018',
    country: 'US',
    director: 'Rodney Rothman, Peter Ramsey, Bob Persichetti',
    story: 'Phil Lord',
    character: 'Steve Ditko',
    screenplay: 'Stan Lee',
    userScores: 89,
    poster: 'images/poster_spiderman.jpg',
  ),
  Movie(
    title: 'Alita: Battle Angel',
    genre: 'Action, Science Fiction, Adventure',
    duration: '2h 2m',
    overview:
    'When Alita awakens with no memory of who she is in a future world she does not recognize, she is taken in by Ido, a compassionate doctor who realizes that somewhere in this abandoned cyborg shell is the heart and soul of a young woman with an extraordinary past.',
    releaseDate: '02/14/2019',
    year: '2019',
    country: 'US',
    director: 'Robert Rodriguez',
    story: 'Robert Rodriguez',
    character: 'Laeta Kalogridis',
    screenplay: 'James Cameron, Laeta Kalogridis',
    userScores: 71,
    poster: 'images/poster_alita.jpg',
  ),
  Movie(
    title: 'Aquaman',
    genre: 'Action, Adventure, Fantasy',
    duration: '2h 24m',
    overview:
    'Once home to the most advanced civilization on Earth, Atlantis is now an underwater kingdom ruled by the power-hungry King Orm. With a vast army at his disposal, Orm plans to conquer the remaining oceanic people and then the surface world. Standing in his way is Arthur Curry, Orm\'s half-human, half-Atlantean brother and true heir to the throne.',
    releaseDate: '12/21/2018',
    year: '2018',
    country: 'US',
    director: 'James Wan',
    story: 'James Wan, Will Beall, Geoff Johns',
    character: 'Paul Norris, Mort Weisinger',
    screenplay: 'David Leslie Johnson-McGoldrick',
    userScores: 69,
    poster: 'images/poster_aquaman.jpg',
  ),
  Movie(
    title: 'Bohemian Rhapsody',
    genre: 'Music, Drama',
    duration: '2h 15m',
    overview:
    'Singer Freddie Mercury, guitarist Brian May, drummer Roger Taylor and bass guitarist John Deacon take the music world by storm when they form the rock \'n\' roll band Queen in 1970. Hit songs become instant classics. When Mercury\'s increasingly wild lifestyle starts to spiral out of control, Queen soon faces its greatest challenge yet – finding a way to keep the band together amid the success and excess.',
    releaseDate: '11/02/2018',
    year: '2018',
    country: 'US',
    director: 'Bryan Singer',
    story: 'Anthony McCarten, Peter Morgan',
    character: 'Peter Morgan',
    screenplay: 'Anthony McCarten',
    userScores: 80,
    poster: 'images/poster_bohemian.jpg',
  ),
  Movie(
    title: 'Cold Pursuit',
    genre: 'Action, Crime, Thriller',
    duration: '1h 59m',
    overview:
    'The quiet family life of Nels Coxman, a snowplow driver, is upended after his son\'s murder. Nels begins a vengeful hunt for Viking, the drug lord he holds responsible for the killing, eliminating Viking\'s associates one by one. As Nels draws closer to Viking, his actions bring even more unexpected and violent consequences, as he proves that revenge is all in the execution.',
    releaseDate: '02/08/2019',
    year: '2019',
    country: 'US',
    director: 'Hans Petter Moland',
    story: 'Hans Petter Moland',
    character: 'Frank Baldwin',
    screenplay: 'Frank Baldwin',
    userScores: 66,
    poster: 'images/poster_cold_persuit.jpg',
  ),
  Movie(
    title: 'Creed II',
    genre: 'Drama',
    duration: '2h 10m',
    overview:
    'Between personal obligations and training for his next big fight against an opponent with ties to his family\'s past, Adonis Creed is up against the challenge of his life.',
    releaseDate: '11/21/2018',
    year: '2018',
    country: 'US',
    director: 'Steven Caple Jr.',
    story: 'Cheo Hodari Coker, Sascha Penn',
    character: 'Sylvester Stallone',
    screenplay: 'Sylvester Stallone, Juel Taylor',
    userScores: 69,
    poster: 'images/poster_creed.jpg',
  ),
  Movie(
    title: 'Fantastic Beasts: The Crimes of Grindelwald',
    genre: 'Adventure, Fantasy, Drama',
    duration: '2h 14m',
    overview:
    'Gellert Grindelwald has escaped imprisonment and has begun gathering followers to his cause—elevating wizards above all non-magical beings. The only one capable of putting a stop to him is the wizard he once called his closest friend, Albus Dumbledore. However, Dumbledore will need to seek help from the wizard who had thwarted Grindelwald once before, his former student Newt Scamander, who agrees to help, unaware of the dangers that lie ahead. Lines are drawn as love and loyalty are tested, even among the truest friends and family, in an increasingly divided wizarding world.',
    releaseDate: '11/16/2018',
    year: '2018',
    country: 'US',
    director: 'David Yates',
    story: 'David Yates',
    character: 'J.K. Rowling',
    screenplay: 'J.K. Rowling',
    userScores: 69,
    poster: 'images/poster_crimes.jpg',
  ),
  Movie(
    title: 'Glass',
    genre: 'Thriller, Drama, Science Fiction',
    duration: "2h 9m",
    overview:
    'In a series of escalating encounters, former security guard David Dunn uses his supernatural abilities to track Kevin Wendell Crumb, a disturbed man who has twenty-four personalities. Meanwhile, the shadowy presence of Elijah Price emerges as an orchestrator who holds secrets critical to both men.',
    releaseDate: '01/18/2019',
    year: '2019',
    country: 'US',
    director: 'M. Night Shyamalan',
    story: 'M. Night Shyamalan',
    character: 'M. Night Shyamalan',
    screenplay: 'M. Night Shyamalan',
    userScores: 75,
    poster: 'images/poster_glass.jpg',
  ),
  Movie(
    title: 'Avengers: Infinity War',
    genre: 'Adventure, Action, Science Fiction',
    duration: "2h 29m",
    overview:
    'As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.',
    releaseDate: '04/27/2018',
    year: '2018',
    country: 'US',
    director: 'Anthony Russo, Joe Russo',
    story: 'Joe Russo',
    character: 'Anthony Russo',
    screenplay: 'Stephen McFeely, Christopher Markus',
    userScores: 88,
    poster: 'images/poster_infinity_war.jpg',
  ),
  Movie(
    title: 'Master Z: Ip Man Legacy',
    genre: 'Action',
    duration: "1h 47m",
    overview:
    'Following his defeat by Master Ip, Cheung Tin Chi tries to make a life with his young son in Hong Kong, waiting tables at a bar that caters to expats. But it\'s not long before the mix of foreigners, money, and triad leaders draw him once again to the fight.',
    releaseDate: '12/26/2018',
    year: '2018',
    country: 'TW',
    director: 'Yuen Woo-ping',
    story: 'Yuen Woo-ping',
    character: 'Edmond Wong',
    screenplay: 'Edmond Wong, Chan Tai-Li',
    userScores: 72,
    poster: 'images/poster_master_z.jpg',
  ),
  Movie(
    title: 'Overlord',
    genre: 'Horror, War, Science Fiction',
    duration: "1h 50m",
    overview:
    'France, June 1944. On the eve of D-Day, some American paratroopers fall behind enemy lines after their aircraft crashes while on a mission to destroy a radio tower in a small village near the beaches of Normandy. After reaching their target, the surviving paratroopers realise that, in addition to fighting the Nazi troops that patrol the village, they also must fight against something else.',
    releaseDate: '11/09/2018',
    year: '2018',
    country: 'US',
    director: 'Julius Avery',
    story: 'Billy Ray',
    character: 'Mark L. Smith',
    screenplay: 'Billy Ray, Mark L. Smith',
    userScores: 70,
    poster: 'images/poster_overlord.jpg',
  ),
  Movie(
    title: 'Spider-Man: Into the Spider-Verse',
    genre: 'Action, Adventure, Animation, Science Fiction, Comedy',
    duration: "1h 57m",
    overview:
    'Miles Morales is juggling his life between being a high school student and being a spider-man. When Wilson \'Kingpin\' Fisk uses a super collider, others from across the Spider-Verse are transported to this dimension.',
    releaseDate: '12/14/2018',
    year: '2018',
    country: 'US',
    director: 'Rodney Rothman, Peter Ramsey, Bob Persichetti',
    story: 'Phil Lord',
    character: 'Steve Ditko',
    screenplay: 'Stan Lee',
    userScores: 89,
    poster: 'images/poster_spiderman.jpg',
  ),
];